import type { DemoUser, Incident } from "./types";

export const demoUser: DemoUser = {
  id: "guard-max",
  name: "Max Cortez",
  email: "max.cortez@shiftlog.demo",
  siteId: "site-harbor",
  siteName: "Harbor Point",
};

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60 * 1000).toISOString();

export const demoIncidents: Incident[] = [
  {
    id: "inc-001",
    type: "access",
    location: "North lobby",
    severity: "medium",
    description: "Visitor attempted entry without an active badge. Identity confirmed and supervisor notified.",
    guardId: "guard-max",
    guardName: "Max Cortez",
    siteId: "site-harbor",
    createdAt: minutesAgo(36),
    handedOver: false,
    reviewed: false,
  },
  {
    id: "inc-002",
    type: "maintenance",
    location: "Garage B",
    severity: "low",
    description: "Broken light fixture reported near the west stairwell. Work order submitted.",
    guardId: "guard-rivera",
    guardName: "Elena Rivera",
    siteId: "site-harbor",
    createdAt: minutesAgo(95),
    handedOver: false,
    reviewed: true,
  },
  {
    id: "inc-003",
    type: "medical",
    location: "Loading dock",
    severity: "high",
    description: "Contractor reported chest pain. Emergency services responded and supervisor secured the area.",
    guardId: "guard-rivera",
    guardName: "Elena Rivera",
    siteId: "site-harbor",
    createdAt: minutesAgo(188),
    handedOver: false,
    reviewed: true,
  },
  {
    id: "inc-004",
    type: "disturbance",
    location: "South courtyard",
    severity: "medium",
    description: "Noise complaint resolved after verbal warning. No further action required.",
    guardId: "guard-chen",
    guardName: "Daniel Chen",
    siteId: "site-harbor",
    createdAt: minutesAgo(310),
    handedOver: true,
    reviewed: true,
  },
  {
    id: "inc-005",
    type: "other",
    location: "Reception",
    severity: "low",
    description: "Found property logged and secured in the supervisor cabinet.",
    guardId: "guard-chen",
    guardName: "Daniel Chen",
    siteId: "site-harbor",
    createdAt: minutesAgo(760),
    handedOver: true,
    reviewed: true,
  },
];
